### ISSUE TITLE
Open API Module 

### ISSUE THREAD

**Issue by jonlamdev** [StatCan/StatCan.OrchardCore#155]
Create an Open API module that provides the ability to:
* render an Open API-based widget
* workflow task (i.e. the client) for making the approrpirate HTTP requests

## Reference
* https://swagger.io/specification/

## Existing Work
* https://swagger.io/tools/swagger-ui/
* https://openapi.tools/

## Related Work
* Orchard CMS Open API generation

**Comment by mfan127** [comment]
The Swagger UI widget is implemented in the StatCan.OrchardCore.OpenAPI module. [https://github.com/StatCan/StatCan.OrchardCore/tree/openapi](url)

The Swagger UI is trying to fetch the swagger.json but is blocked by the Content Security Policy. The rendered UI is shown below.
![image](https://user-images.githubusercontent.com/62428476/101958919-4a42e100-3bd2-11eb-80e8-44b8f595a651.png)

**Comment by jptissot** [comment]
closed by #169
