### ISSUE TITLE
Modal title occluded by close ("x") button

### ISSUE THREAD

**Issue by brendangadd** [StatCan/StatCan.OrchardCore#16]
Long modal titles can be occluded by the modal's close button. This is the case for "Request a Kubeflow namespace" modal, tested on mobile Firefox.

**Comment by bbronzan** [comment]
This is a tricky bugger, and we're looking into it thanks!

**Comment by M-A-Boucher** [comment]
Fixed in https://github.com/StatCan/StatCan.OrchardCore/commit/c2e413cbad86965291f7eee3e9bf37870783fc64
