### ISSUE TITLE
IE11 Testing: Round 1

### ISSUE THREAD

**Issue by bbronzan** [StatCan/StatCan.OrchardCore#18]
### (Try adding this to head... apparently this corrects the CSS background-size: cover)
`<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">`

## 2. **Feedback modal:** Button slightly overlaps bottom of text input
![image (2)](https://user-images.githubusercontent.com/62296192/82441463-f02ed280-9a6b-11ea-963a-58e6f84f11a2.png)

## 3. **section-panel:** Description text just keeps goooooooooooing!
![image (4)](https://user-images.githubusercontent.com/62296192/82441507-0341a280-9a6c-11ea-94da-7a0e4b772a16.png)
![image (3)](https://user-images.githubusercontent.com/62296192/82441478-f58c1d00-9a6b-11ea-8469-7fd471f8396f.png)

## 4. **Add-on action modal:** Is a bit of a mess, but likely caused by the text flow.
![image (5)](https://user-images.githubusercontent.com/62296192/82441531-0fc5fb00-9a6c-11ea-9dd6-77757939a4bb.png)

## 5. **Account modal:** Mild spacing issue
![image (6)](https://user-images.githubusercontent.com/62296192/82441542-17859f80-9a6c-11ea-981e-ebf21595629d.png)

**Comment by M-A-Boucher** [comment]
Resolved in https://github.com/StatCan/StatCan.OrchardCore/commit/c2e413cbad86965291f7eee3e9bf37870783fc64.
