### ISSUE TITLE
Things that are unpolished or TODOs

### ISSUE THREAD

**Issue by bbronzan** [StatCan/StatCan.OrchardCore#21]
Let's get a simple list going on anything we know that still needs to be tweaked, but works well enough to user test during the hackathon next week.

**Comment by bbronzan** [comment]
When namespace request fails:

open the modal on redirect  
OR  
(if possible, I imagine it needs AJAX) show the error in the modal without navigating away

**Comment by bbronzan** [comment]
When namespace request sent:

navigate back down to the section on redirect
(almost like they didn't redirect after all)

**Comment by bbronzan** [comment]
Username and email are not editable in the account modal

**Comment by bbronzan** [comment]
Add-on options ("request a namespace" and "add a dashboard") are uni-lingual in the code and need to be broken out into the locale.

**Comment by bbronzan** [comment]
Google Translate will be used for the French until the text comes back from Translation Services.

(Everyone feel free to highlight obvious errors and suggest fixes)

**Comment by bbronzan** [comment]
No spam protection on feedback or namespace features. 

Add captcha v3 to protect them and not burden the user.

**Comment by M-A-Boucher** [comment]
> Add-on options ("request a namespace" and "add a dashboard") are uni-lingual in the code and need to be broken out into the locale.

Done

**Comment by bbronzan** [comment]
Apply the new hover effect (colour and upwards movement) to the other primary buttons:
- LOG IN (in hero)
- Top-right buttons
- "More virtual labs"
- anything else I missed

**Comment by bbronzan** [comment]
Language toggle works fine the first click or so, then you have to click it twice to actually change. Sometimes the page changes but the button label doesn't.

**Comment by bbronzan** [comment]
Safari iPad hero almost fits... the FIP is cut off slightly

**Comment by bbronzan** [comment]
Change the "Email" input on ExternalLoginCallback to an "email" input so mobile browsers use the special keyboard.

**Comment by bbronzan** [comment]
Chrome iPad her FIP is completely cut off. (not a huge deal)

Bottom FIP sig is slightly cut off too.

**Comment by bbronzan** [comment]
Firefox Focus mobile hides the feedback modal when the bottom link is tapped. 

The modal displays and when the text area gets focus, it scrolls away. 

The top link didn't do that though... strange!

**Comment by bbronzan** [comment]
Firefox Focus mobile hides the namespace modal when the input has focus and the keyboard comes up.

(like the issue above with the feedback modal)

**Comment by M-A-Boucher** [comment]
> Change the "Email" input on ExternalLoginCallback to an "email" input so mobile browsers use the special keyboard.

Done.

**Comment by M-A-Boucher** [comment]
> Apply the new hover effect (colour and upwards movement) to the other primary buttons:
> 
> * LOG IN (in hero)
> * Top-right buttons
> * "More virtual labs"
> * anything else I missed

Done. Button contrast changes will be a separate issue.

**Comment by bbronzan** [comment]
No new issue will be created for this because it will be taken care of in https://github.com/StatCan/StatCan.OrchardCore/issues/33

> When namespace request sent:
> 
> navigate back down to the section on redirect
> (almost like they didn't redirect after all)

No new issue will be created for this because it will be taken care of by

**Comment by bbronzan** [comment]
Finished items have the 👍 

Items moved to their own ticket have the 🚀
