### ISSUE TITLE
Register feedback in a location accessible to the project

### ISSUE THREAD

**Issue by brendangadd** [StatCan/StatCan.OrchardCore#24]
Feedback is registered to a Slack channel that's limited to the Digital Innovation team. Moving it somewhere visible to Project 22 members is a manual process.

Register feedback (automatically) to a location that is accessible to our support and research staff. Let's start with `#feedback-notifications` in the Slack support workspace.

**Comment by M-A-Boucher** [comment]
We can do this easily/today if a Slack hook is provided.

**Comment by bbronzan** [comment]
> Feedback is registered to a Slack channel that's limited to the Digital Innovation team. Moving it somewhere visible to Project 22 members is a manual process.
> 
> Register feedback (automatically) to a location that is accessible to our support and research staff. Let's start with `#feedback-notifications` in the Slack support workspace.

That's no problem, and the plan has already been documented in this ticket: https://github.com/StatCan/StatCan.OrchardCore/issues/24

Manually forwarding a copy to your Slack/repo was only a temporary measure.

**Comment by bbronzan** [comment]
As per https://github.com/StatCan/StatCan.OrchardCore/issues/14#issuecomment-633659554

Instead of GitHub, the DAaaS folks decided to go with a Slack channel endpoint for the feedback.

Integrated and tested. Good to go.
