### ISSUE TITLE
Add support for Helm Chart Secrets

### ISSUE THREAD

**Issue by IlyA-stc** [StatCan/StatCan.OrchardCore#255]
Incorporate Helm Chart secrets with OrchardCore

**Comment by jptissot** [comment]
This was completed here: https://github.com/StatCan/charts/commit/2146f661bb6f8b38e7b1a117f0cff40e24599c8b#diff-236cbff014d113d787b0c7e7088e53cf78b20fdd5e9ab49e3e1c34039fceb4f9
