### ISSUE TITLE
[VueForms] Refactor / improvements

### ISSUE THREAD

**Issue by jptissot** [StatCan/StatCan.OrchardCore#280]
After using the module for a while, it has become evident that we could benefit from some refactoring and improvements.

- Add a single template instead of the flow editor
- Reorganize tabs and fields 
- Switch to the Moncao editor
- Add a handy debug mode + allow users to add debug information in their server side scripts

**Comment by Line4GitHub** [comment]
Can you provide a 
sample solution/project that uses VueForms, Scripts and Workflows to implement CRUD operations of content items of some custom content types
and
Tutorials similar with 
Orchard Core CRUD Operations with a Custom Content Type (https://www.youtube.com/watch?v=wXreQDjtuFc) 
or
Orchard Core Workflows Walkthrough: Content Approval (http://www.ideliverable.com/blog/orchard-core-workflows-walkthrough-content-approval) ?
Thank you very much!

**Comment by jptissot** [comment]
> Can you provide a
> sample solution/project that uses VueForms, Scripts and Workflows to implement CRUD operations of content items of some custom content types
> and
> Tutorials similar with
> Orchard Core CRUD Operations with a Custom Content Type (https://www.youtube.com/watch?v=wXreQDjtuFc)
> or
> Orchard Core Workflows Walkthrough: Content Approval (http://www.ideliverable.com/blog/orchard-core-workflows-walkthrough-content-approval) ?
> Thank you very much!

Yes, for sure. I plan on writing a recipe that creates a complete example soon.

**Comment by Line4GitHub** [comment]
Thank you very much!

**Comment by jptissot** [comment]
I might do a demo at the Orchard meeting as well that will be available on Youtube.

**Comment by jptissot** [comment]
Created the #283 issue for this

**Comment by Line4GitHub** [comment]
Thank you very much!
for 我可能會在果園會議上做一個演示，以及將在Youtube上提供。
