### ISSUE TITLE
Editable profile

### ISSUE THREAD

**Issue by M-A-Boucher** [StatCan/StatCan.OrchardCore#30]
Allow users to change their profile (name and profile). Investigate if it's possible to change account name in Orchard.

_Originally posted by @bbronzan in https://github.com/StatCan/StatCan.OrchardCore/issues/21#issuecomment-632881639_

**Comment by jptissot** [comment]
Have a look at https://github.com/EtchUK/Etch.OrchardCore.UserProfiles

**Comment by jptissot** [comment]
This module could be used by multiple applications.

**Comment by jptissot** [comment]
This is now possible with the latest version
