### ISSUE TITLE
VueForms Template Model Data

### ISSUE THREAD

**Issue by emrahtokalak** [StatCan/StatCan.OrchardCore#344]
Hi @jptissot

I can't access {{ Model }} data in Vueform template field, returns null. {{ Model | console_log }} is same. I can access the User data, I wrote this just to test it.

I am using Shape as follows;

`{% assign VueFormsWidget = Model.ContentItem.Content.FlowPart.Widgets.first %}
        {% assign VueFormsId = VueFormsWidget.VueFormReference.FormReference.ContentItemIds.first | content_item_id %}
        {% assign VueFormsShape = VueFormsId | shape_build_display %}
        {% shape_add_properties VueFormsShape category_items: Model.ContentItem.Content.Categories.ContentItems,
        currentpage: Model.ContentItem %}
        {{ VueFormsShape | shape_render }}`

<img width="995" alt="Screenshot 2023-01-21 at 19 54 51" src="https://user-images.githubusercontent.com/90242/213877864-c83c71e3-7554-48f8-95d4-86e7afdaa037.png">

Where could I be doing wrong?

**Comment by jptissot** [comment]
@emrahtokalak Hey, I just logged back in to Github after some time off. Let me know if you are still having this issue.

**Comment by emrahtokalak** [comment]
Hi @jptissot,

Still can't access data {{ Model }} in Vueform template field returns null.

https://github.com/OrchardCMS/OrchardCore/discussions/7030 I tried using the IShapeTableProvider suggested here, but with no results.

**Comment by emrahtokalak** [comment]
I solved the problem.

By sending Model data instead of ContentItem, I was able to get the data I wanted.

https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.VueForms/Views/VueForm-CommonTemplate.cshtml#L15

**Comment by emrahtokalak** [comment]
I solved the problem.

By sending Model data instead of ContentItem, I was able to get the data I wanted.

https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.VueForms/Views/VueForm-CommonTemplate.cshtml#L15
