### ISSUE TITLE
Language toggle only works on the first few clicks

### ISSUE THREAD

**Issue by bbronzan** [StatCan/StatCan.OrchardCore#35]
Language toggle works fine the first click or so, then you have to click it twice to actually change. Sometimes the page changes but the button label doesn't.

_Originally posted by @bbronzan in https://github.com/StatCan/StatCan.OrchardCore/issues/21#issuecomment-632939272_

**Comment by jptissot** [comment]
I think this might be a cookie issue.

**Comment by jptissot** [comment]
Turns out this was a caching issue. You can't cache a Shape that injects html into zones because that code does not get evaluated when a user hits the cache.

Fixed by https://github.com/StatCan/StatCan.OrchardCore/commit/c49c786f063c050f52cac5ffbe5658cbaa23890f
