### ISSUE TITLE
Change the "Email" input on ExternalLoginCallback to an "email" input so mobile browsers use the special keyboard.

### ISSUE THREAD

**Issue by bbronzan** [StatCan/StatCan.OrchardCore#37]
Change the "Email" input on ExternalLoginCallback to an "email" input so mobile browsers use the special keyboard.

_Originally posted by @bbronzan in https://github.com/StatCan/StatCan.OrchardCore/issues/21#issuecomment-632959388_

**Comment by M-A-Boucher** [comment]
Fixed in https://github.com/StatCan/StatCan.OrchardCore/commit/f583b7f2e8c8924e8ab61344e533e88de8180d61
