### ISSUE TITLE
Setup testing in CI

### ISSUE THREAD

**Issue by jptissot** [StatCan/StatCan.OrchardCore#4]
Setup cypress tests with github actions

**Comment by justbert** [comment]
I've been looking into Cypress more and more. It seems way nicer than all the work I had to do to build a Selenium testing system.

**Comment by jptissot** [comment]
@justbert I have cypress already setup for our "Old" orchard repository. I also started working on cypress tests for Orchard here https://github.com/OrchardCMS/OrchardCore/tree/jptissot/cypress

**Comment by justbert** [comment]
Thank you! I'll take a look! :D
