### ISSUE TITLE
Amend automated PR for muti-user profiles

### ISSUE THREAD

**Issue by justbert** [StatCan/StatCan.OrchardCore#40]
Would it be possible to amend the automated process that creates PRs that add Profile manifests to the platform (#2):

- The filename should follow the convention: **profile-**[-a-zA-Z0-9]+**.yaml**
- The file should be placed in /config/kubeflow/

Remove the plugin from the Manifest template. @zachomedia says we are no longer using this.

If possible, the PR should be assigned to the DAaaS project.

**Comment by jptissot** [comment]
> If possible, the PR should be assigned to the DAaaS project.

@justbert do you mean make the pr to the daaas repository? Or assign a user?

**Comment by justbert** [comment]
When making a PR, it can be assigned to a project so that it shows up in the review column.

**Comment by jptissot** [comment]
I don't think the github api v3 supports setting the project unfortunately: 
https://developer.github.com/v3/pulls/

**Comment by justbert** [comment]
Ah okay! That's too bad! Thanks for looking into it :)

**Comment by jptissot** [comment]
We could assign a user if that helps?

**Comment by jptissot** [comment]
The recommendations in the issue description have been made. The only thing missing is a validation that the namespace is alphanumeric (with dashes).

**Comment by M-A-Boucher** [comment]
I believe characters that are not alphanumeric or dashes are being filtered out of the text field input. So it shouldn’t be possible to submit a namespace request that doesn’t fit the convention.

**Comment by brendangadd** [comment]
@jptissot @M-A-Boucher If there's more to do to enforce the naming constraints then that can go in a new issue if you'd like. A person still needs to review the PR before the namespace is created.

**Comment by justbert** [comment]
Things look good! Thanks!
