### ISSUE TITLE
Re-enable registration feature and add on-boarding instructions

### ISSUE THREAD

**Issue by bbronzan** [StatCan/StatCan.OrchardCore#41]
Turn the registration feature back on and include account-related pages as necessary.

**Comment by bbronzan** [comment]
@brendangadd Since users are required to use the Azure SSO with their Cloud account and they need to be on-boarded before using the AAW, is there a set of instructions or contact details we could add to the public-facing "Register" page to prompt new users?

**Comment by brendangadd** [comment]
@bbronzan Since the platform is not yet available to the public, I'm not sure we can give meaningful registration information on public internet just yet.

**Comment by bbronzan** [comment]
Ok no problem, so the current on-boarding of users will remain the same then? If so, the ability to register wouldn't need to be enabled yet so we can turn it off again until a later time. I guess this ticket could be placed back into the backlog for now. Let me know.

**Comment by jptissot** [comment]
Closing since we handed off this component.
