### ISSUE TITLE
[Feature] VueForms Module

### ISSUE THREAD

**Issue by jptissot** [StatCan/StatCan.OrchardCore#5]
Port existing forms module with some improvements

- Single controller for submissions
- Integrated server side validation
- Form submission script
- Form Submitted workflow hook
- Load Vuetify / VeeValidate librairies
- Implement VueComponent widget that allows us to write simple VueComponents in the admin

**Comment by brendangadd** [comment]
@jptissot @M-A-Boucher Was this done as part of the other things that were implemented (e.g. feedback form)?

**Comment by jptissot** [comment]
No, this is still a WIP. I haven't had a chance to finish the implementation. Forms work in OC but are a bit tedious to setup. This module will help us setup forms with better server side validation and Ajax submissions.

**Comment by M-A-Boucher** [comment]
This will fix: https://github.com/StatCan/StatCan.OrchardCore/issues/21#issuecomment-632880798_

**Comment by jptissot** [comment]
Fixed in https://github.com/StatCan/StatCan.OrchardCore/commit/5ffdbf35975c4200623456f250975ef9f552e320
