### ISSUE TITLE
Implement "Digital" Theme

### ISSUE THREAD

**Issue by jonlamdev** [StatCan/StatCan.OrchardCore#52]
* ensure content parts have meaningful names

## Site-wide 
- [ ] Navigation Bar 
- [ ] Page header
- [ ] Footer 

## Front page
- [ ] Section: Hero
- [ ] Section: digital background
- [ ] Section: no background
- [ ] Section: dark background 

## Page
- [ ] Section: title
- [ ] Section: list layout
- [ ] Section: tri-card layout  
- [ ] Section: split  layout

**Comment by jptissot** [comment]
@M-A-Boucher how are we doing on this one ?

**Comment by M-A-Boucher** [comment]
This is done.
