### ISSUE TITLE
Change resource documents in the documentation section

### ISSUE THREAD

**Issue by Colette-G** [StatCan/StatCan.OrchardCore#72]
Change the documentation section (https://kubeflow.covid.cloud.statcan.ca/) to point to documents specific to our environment.

**Comment by brendangadd** [comment]
@Colette-G This is covered by StatCan/kubeflow#22. Was this supposed to be the issue for the "Need help getting started?" stuff?

**Comment by jonlamdev** [comment]
Closing, since this is unrelated to Orchard Core. Thanks for submitting an issue. Reopen if needed.
