### ISSUE TITLE
Add French content

### ISSUE THREAD

**Issue by brendangadd** [StatCan/StatCan.OrchardCore#8]
I18n is supported, but need to add translated content to the French version.

**Comment by bbronzan** [comment]
Here is a .docx file with all the text and screenshots for context.
[P22 Portal Translation.docx](https://github.com/StatCan/StatCan.OrchardCore/files/4669108/P22.Portal.Translation.docx)

Feel free to send this to translation services anytime.

**Comment by abhinavgurung** [comment]
Translation sent , should have it by tonight or tomorrow.

**Comment by abhinavgurung** [comment]
@bbronzan  here is the translated version

[Portal.French.docx](https://github.com/StatCan/StatCan.OrchardCore/files/4689963/Portal.French.docx)
