### ISSUE TITLE
VueForms:  Add way to return workflow errors to the client

### ISSUE THREAD

**Issue by M-A-Boucher** [StatCan/StatCan.OrchardCore#85]
Current formSubmitError handles form validation errors. However, it would be nice to have signals from the workflow to allow custom errors sent to the front-end when part of the workflow fails.

**Comment by jptissot** [comment]
Fixed in https://github.com/StatCan/StatCan.OrchardCore/commit/95bd9301e880ff752877a1f4ae0f04eaf5d1f1e6
