### ISSUE TITLE
[Feature] GitHub workflow tasks

### ISSUE THREAD

**Issue by jptissot** [StatCan/StatCan.OrchardCore#9]
Build workflow tasks that allow a user to:

- Create a GitHub branch
- Create Single file commits to branch and push them
- Create a GitHub Pull Request for any branch

These tasks should use an api token that is encrypted in the database.

**Comment by brendangadd** [comment]
@jptissot Is this a prerequisite for StatCan/daaas#2?

**Comment by jptissot** [comment]
@brendangadd Yes. 
I thought we could simply use the GitHub Api (via http request as supported by OC's workflows) but it turns out this was harder than I initially thouught. So, I am making a OC Module that uses Octokit.net to interact with the api. This will be reusable for all sites as it is being implemented in a OC Module.
